app = 'weibo-rss-sparkling-bush-4922'
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = 'nrt'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
